name: release-please
on:
  push:
    branches: [master]
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@7450acbae0eabb8558adc8f11e94a94bfb77acbb # main
    secrets: inherit
