name: release-please
on:
  push:
    branches: [master]
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@5a06bdfe75ead7614f6a2bdddfa00f60b4cc9c9b # main
    secrets: inherit
