name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [master]
jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-scorecard.yml@5a06bdfe75ead7614f6a2bdddfa00f60b4cc9c9b # main
